In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df_kuliner = pd.read_excel("Dataset Kuliner.xlsx")
df_kuliner.head()

,No,Nama Tempat,Kategori,Jam Buka,Jam Tutup,GPS Location,HTM Min,HTM Max,Keterangan,Rating,Status
0,1,Srengenge Wetan,Tradisional,09:00:00,21:00:00,"-8.2065605, 114.3734445",50000.0,100000.0,Pada hari Sabtu buka pukul 10:00:00 AM dan tut...,"4,5",NaN
1,2,Rodjo Nogo,Tradisional,08:00:00,21:00:00,"-8.56482115813169, 114.10696668570581",20000.0,100000.0,"Selain restauran, rodjo nogo juga menyediakan ...","4,2",NaN
2,3,Singosing Cafe & Resto,Inovatif,10:00:00,22:00:00,"-8.3123694, 114.2441926",20000.0,140000.0,Area luas dapat digunakan sebagai acara pertem...,"4,6",NaN
3,4,Warung Seblang,Inovatif,09:00:00,21:00:00,"-8.3007263, 114.2459139",20000.0,40000.0,Area Restoran dapat digunakan sebagai acara pe...,"4,1",NaN
4,5,Gen Gentong Resto,Inovatif,10:00:00,22:00:00,"-8.3058414, 114.2169849",25000.0,50000.0,Kamis tutup,"4,4",NaN

In [ ]:
# Bersihkan rating
df_kuliner['Rating'] = df_kuliner['Rating'].astype(str).str.replace(',', '.')
df_kuliner['Rating'] = pd.to_numeric(df_kuliner['Rating'], errors='coerce')

df_kuliner['Rating'] = df_kuliner['Rating'].fillna(0)

df_kuliner.head()

,No,Nama Tempat,Kategori,Jam Buka,Jam Tutup,GPS Location,HTM Min,HTM Max,Keterangan,Rating,Status
0,1,Srengenge Wetan,Tradisional,09:00:00,21:00:00,"-8.2065605, 114.3734445",50000.0,100000.0,Pada hari Sabtu buka pukul 10:00:00 AM dan tut...,4.5,NaN
1,2,Rodjo Nogo,Tradisional,08:00:00,21:00:00,"-8.56482115813169, 114.10696668570581",20000.0,100000.0,"Selain restauran, rodjo nogo juga menyediakan ...",4.2,NaN
2,3,Singosing Cafe & Resto,Inovatif,10:00:00,22:00:00,"-8.3123694, 114.2441926",20000.0,140000.0,Area luas dapat digunakan sebagai acara pertem...,4.6,NaN
3,4,Warung Seblang,Inovatif,09:00:00,21:00:00,"-8.3007263, 114.2459139",20000.0,40000.0,Area Restoran dapat digunakan sebagai acara pe...,4.1,NaN
4,5,Gen Gentong Resto,Inovatif,10:00:00,22:00:00,"-8.3058414, 114.2169849",25000.0,50000.0,Kamis tutup,4.4,NaN

In [ ]:
ratings_kuliner = pd.DataFrame({
    'user_id': np.random.randint(1, 15, 80),
    'kuliner': np.random.choice(df_kuliner['Nama Tempat'], 80),
    'rating': np.random.randint(3, 6, 80)
})

ratings_kuliner

    user_id                        kuliner  rating
0        14             Warung kali sodong       3
1         1                          Berco       4
2        10          Gesah Coffe & Culture       3
3         8                   Maskot Resto       5
4         6  Gandrung Area Istana Gandrung       5
..      ...                            ...     ...
75        7                  Camping resto       3
76        9                    Osing Aslay       4
77       14                    Osing Aslay       4
78        1                Alas Restaurant       4
79        1                    Warung Biru       5

[80 rows x 3 columns]

In [ ]:
saved_kuliner = pd.DataFrame({
    'user_id': np.random.randint(1, 15, 40),
    'kuliner': np.random.choice(df_kuliner['Nama Tempat'], 40),
    'saved': 1
})

saved_kuliner

    user_id                                 kuliner  saved
0         2                            Warung K-jon      1
1        10                            Cafe Thalita      1
2        11          Warung Pakdhe Panjang Jiwo BWI      1
3        10                          D'cingkir cafe      1
4         6              Sampoerna Resto Banyuwangi      1
5         8                          Cafe cangkring      1
6         8                   Bibiba Cafe And Grill      1
7        10                   Wong Osing Banyuwangi      1
8        12                    Camp Resto and Caffe      1
9         2               Omah pakel cafe and resto      1
10        6                   Warung Pangklang Asri      1
11        8                   Gesah Coffe & Culture      1
12        3                        Resto indrawangi      1
13        4              Ujung Jawa cafe and eatery      1
14        1              Casabanyu Restaurant & Bar      1
15       10                    Resto lesehan rida 2      1
16        8  Warung Ayam Betutu Spesial Mbak Timah       1
17       12                     Pondok jasmin beach      1
18        7          Warung Pakdhe Panjang Jiwo BWI      1
19        4                     Kantin Pia Glenmore      1
20       14                            Hutan Tropis      1
21        2                     Dapur Jo Banyuwangi      1
22        9          Warung Pakdhe Panjang Jiwo BWI      1
23       11                 Senja. co cafe n resto       1
24       12                    Dapoer thata kemiren      1
25       13                  PanggonMu (Warung PM)       1
26        7                 OKU Guest House & Resto      1
27        8                            Waduk Lecari      1
28        5                            Seafood Sobo      1
29        6                       Warung suku osing      1
30        3                  Sego Tempong Mbok Wah       1
31       10                     Warung Dalam Negeri      1
32       11                      Restoku Chen-Chen       1
33        9               Rumah Makan Duta Kalibaru      1
34        9              Sampoerna Resto Banyuwangi      1
35        9   Wahoo Restaurant Hotel Ketapang Indah      1
36        9                       Langgeng Kitchen       1
37        8                            Adarasa Cafe      1
38        6     Daipoeng Simpang Blimbingsari (DSB)      1
39        6                         Warung Seblang       1

In [ ]:
interaction_kuliner = pd.merge(
    ratings_kuliner,
    saved_kuliner,
    on=['user_id','kuliner'],
    how='outer'
).fillna(0)

interaction_kuliner['score'] = (
    interaction_kuliner['rating'] +
    interaction_kuliner['saved']
)

In [ ]:
user_item_kuliner = interaction_kuliner.pivot_table(
    index='user_id',
    columns='kuliner',
    values='rating'
).fillna(0)

user_item_kuliner.head()

kuliner,1911 Cafe & Resto,Ajeg Resto Banyuwangi,Arjuna Cafe & Resto,Ayam Betutu Hobby Mangan Banyuwangi,Ayam Kesrut Kanggo Riko,Baron Ndut's Steak & Burgers Banyuwangi,Bebek Songkem Taretan,Bibiba Cafe And Grill,Cafe Resto & Glamping Pinggir Lepen,Cafe Thalita,...,Warung Ndeso Rajwa,Warung Pangklang Asri,Warung Puthuk Mbok Misnah,Warung bu Supik,Warung deso menur,Warung ikan bakar salsabila,Warung kali sodong,Wong Osing Banyuwangi,Yogi Resto & villa,pelabuhan rakyat pantai boom
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,5.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [ ]:
similarity_kuliner = cosine_similarity(user_item_kuliner)

similarity_kuliner_df = pd.DataFrame(
    similarity_kuliner,
    index=user_item_kuliner.index,
    columns=user_item_kuliner.index
)

In [ ]:
def get_cf_kuliner(user_id):

    similar_users = similarity_kuliner_df[user_id]\
        .sort_values(ascending=False)[1:6]

    similar_users_index = similar_users.index

    rekomendasi = interaction_kuliner[
        interaction_kuliner['user_id'].isin(similar_users_index)
    ]

    rekomendasi = rekomendasi.sort_values(
        by='rating',
        ascending=False
    )

    return rekomendasi['kuliner'].unique()

In [ ]:
def content_based_kuliner(
    kuliner_list,
    kategori,
    budget_min,
    budget_max,
    rating_min
):

    filtered = df_kuliner[
        (df_kuliner['Nama Tempat'].isin(kuliner_list)) &
        (df_kuliner['Kategori'].isin(kategori)) &
        (df_kuliner['HTM Min'] >= budget_min) &
        (df_kuliner['HTM Max'] <= budget_max) &
        (df_kuliner['Rating'] >= rating_min)
    ]

    return filtered

In [ ]:
def hybrid_kuliner(
    user_id,
    kategori,
    budget_min,
    budget_max,
    rating_min
):

    cf_result = get_cf_kuliner(user_id)

    # fallback jika CF sedikit
    if len(cf_result) < 5:
        cf_result = df_kuliner['Nama Tempat']

    final = content_based_kuliner(
        cf_result,
        kategori,
        budget_min,
        budget_max,
        rating_min
    )

    final = final.sort_values(
        by='Rating',
        ascending=False
    )

    return final

In [ ]:
hasil_kuliner = hybrid_kuliner(
    user_id=8,
    kategori=['Inovatif', 'Tradisional'],
    budget_min=0,
    budget_max=100000,
    rating_min=4.5
)

print(hasil_kuliner[['Nama Tempat','Kategori', 'HTM Min', 'HTM Max', 'Rating']])

                                           Nama Tempat     Kategori  HTM Min  \
170                                         Fresh food     Inovatif  25000.0
176                                   Kedai Omah Gumuk     Inovatif  25000.0
183                                     Cafe cangkring     Inovatif  10000.0
144                       Ikan Asap Jangkar Banyuwangi     Inovatif  25000.0
171                        Warung ikan bakar salsabila     Inovatif  25000.0
63                          Jukung Resto & Nidom Coffe     Inovatif  25000.0
88                          Jukung Resto & Nidom Coffe  Tradisional  25000.0
9    Warung Mbok Sul (WSL) Food & Beverages Banyuwa...     Inovatif  25000.0
126                         Volcano Resto dan Homestay     Inovatif  20000.0
160                              Gesah Coffe & Culture     Inovatif  25000.0
191                               Urup-urup Cafe Resto     Inovatif  25000.0

      HTM Max  Rating
170   50000.0     5.0
176   75000.0     4.8
183   20000.0     4.7
144   75000.0     4.7
171  100000.0     4.6
63    60000.0     4.6
88    50000.0     4.6
9    100000.0     4.5
126   60000.0     4.5
160   75000.0     4.5
191   75000.0     4.5

In [ ]:
cf_result = get_cf_kuliner(2)
cf_result

array(['Arjuna Cafe & Resto', 'Warung Desa Bu Dewi', 'Warung K-jon',
       'Daipoeng Simpang Blimbingsari', 'Rumah Budaya Osing',
       'Sun Osing Beach', "D'calma Cafe Resto", 'Ayam Kesrut Kanggo Riko',
       'Ayam Betutu Hobby Mangan Banyuwangi', 'Yogi Resto & villa ',
       'Omah Kiyambak (OMKIM) Cafe & resto', 'Ujung Jawa cafe and eatery',
       'Warung Ndeso Rajwa', 'Dapoer Umma', 'Gesah Coffe & Culture',
       'Omyah Kemiren', 'Cafe cangkring', 'Kedai Omah Gumuk',
       'Sego Tempong Mbok Wah ', 'Glen Futsal Coffee & Resto',
       'Seafood Sobo', 'Umarasa Cafe & Resto ',
       'Rumah Makan Duta Kalibaru', 'RM. Sate Kambing Cak Bagong',
       'Warung ikan bakar salsabila', 'Pesantogan Kemangi',
       'Volcano Resto dan Homestay', 'Warung Biru', 'Cafe Thalita',
       'Monggo Kerso BWI', 'Fresh food', 'Ikan Asap Jangkar Banyuwangi',
       'Urup-urup Cafe Resto', 'Senja. co cafe n resto ',
       'Le-Roban Rogojampi', 'Cafe Resto & Glamping Pinggir Lepen',
       'Depot Sari Agung Gede',
       'Kembang langit Traditional Restoran & Cafe', 'Resto Pule',
       'Pondok Lumpang'], dtype=object)